import { Inter } from 'next/font/google';
import './styles/globals.css';
import Header from './components/structure/Header';
import Footer from './components/structure/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				<main id='content'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
